spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DATASOURCE_IP}/${SPRING_DATASOURCE_DBNAME}${SPRING_DATASOURCE_SCHEAMA}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none